export default [
  {
    url: 'SUMMERPOSE_2m12s.mp3',
    name: 'Summer Pose',
    fadeInStart: 0,
    start: 7,
    end: 16,
    fadeOutEnd: 25,
    volume: 100,
    on: true,
  },
  {
    url: 'DIN_POSE1.mp3',
    name: 'Din pose 1',
    fadeInStart: 14,
    start: 27,
    end: 34,
    fadeOutEnd: 39,
    volume: 100,
    on: true,
  },
  {
    url: 'MUSIC_POST1.mp3',
    name: 'Music Pose 1',
    fadeInStart: 23,
    start: 30,
    end: 36,
    fadeOutEnd: 44,
    volume: 100,
    on: true,
  },
  {
    url: 'POSE_1.mp3',
    name: 'Pose 1',
    fadeInStart: 29,
    start: 39,
    end: 47,
    fadeOutEnd: 57,
    volume: 100,
    on: true,
  },
  {
    url: 'DIN_POSE2.mp3',
    name: 'Dim pose 2',
    fadeInStart: 55,
    start: 64,
    end: 68,
    fadeOutEnd: 76,
    volume: 100,
    on: true,
  },
  {
    url: 'MUSIC_POSE2.mp3',
    name: 'Music pose 2',
    fadeInStart: 67,
    start: 75,
    end: 79,
    fadeOutEnd: 87,
    volume: 100,
    on: true,
  },
  {
    url: 'POSE_2.mp3',
    name: 'Pose 2',
    fadeInStart: 69,
    start: 86,
    end: 92,
    fadeOutEnd: 96,
    volume: 100,
    on: true,
  },
  {
    url: 'SUMMERPOSE_2m12s.mp3',
    name: 'Summer Pose',
    fadeInStart: 90,
    start: 94,
    end: 96,
    fadeOutEnd: 100,
    volume: 100,
    on: true,
  },
  {
    url: 'VOICES_2m2s.mp3',
    name: 'VOICES 1',
    fadeInStart: 3,
    start: 9,
    end: 14,
    fadeOutEnd: 24,
    volume: 100,
    on: true,
  },
  {
    url: 'VOICES_2m2s.mp3',
    name: 'VOICES 2',
    fadeInStart: 91,
    start: 97,
    end: 99,
    fadeOutEnd: 100,
    volume: 42,
    on: true,
  },
  {
    url: 'VOICES_2m2s.mp3',
    name: 'VOICES 3',
    fadeInStart: 32,
    start: 35,
    end: 39,
    fadeOutEnd: 44,
    volume: 0,
    on: true,
  },
];
